# Generated by Django 4.2.11 on 2024-03-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friendly_name', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Trade'), (2, 'Private')], null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=27, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=27, null=True)),
                ('city_region', models.CharField(blank=True, max_length=27, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_terms', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Payment in advance'), (2, '7 days'), (3, '14 days'), (4, '30 days'), (5, '60 days')], null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
