# Generated by Django 4.2.11 on 2024-03-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('make', models.CharField(blank=True, max_length=27, null=True)),
                ('model', models.CharField(blank=True, max_length=27, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
