# Generated by Django 4.2.11 on 2024-03-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
