# Generated by Django 4.2.11 on 2024-03-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=10, null=True)),
                ('invoice_int', models.PositiveIntegerField(editable=False, null=True)),
                ('date_in', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Ready for processing'), (3, 'Ready for verification'), (4, 'Sent to customer'), (5, 'Work on hold'), (6, 'Complete')], null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('sub_total', models.PositiveIntegerField(blank=True, null=True)),
                ('grand_total', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.vehicle')),
            ],
        ),
    ]
