# Generated by Django 4.2.11 on 2024-03-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_to_company', models.PositiveIntegerField(blank=True, null=True)),
                ('price_to_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=27)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('hours', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour', to='invoice.invoice')),
            ],
            options={
                'verbose_name_plural': 'Labour',
            },
        ),
    ]
