# Generated by Django 4.2.11 on 2024-03-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_customer_id_vehicle_customer'),
        ('invoice', '0003_rename_invoice_int_invoice_inv_integer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Work on hold'), (2, 'Open'), (3, 'Ready for processing'), (4, 'Ready for verification'), (5, 'Sent to customer'), (6, 'Complete')], null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.vehicle'),
        ),
    ]
