# Generated by Django 4.2.11 on 2024-03-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_uniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='uniqueId',
            new_name='unique_id',
        ),
    ]
