# Generated by Django 4.2.11 on 2024-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_part_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='subtotal',
            new_name='total',
        ),
    ]
