# Generated by Django 4.2.11 on 2024-04-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_rename_subtotal_part_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='subtotal',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='labour',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='title',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
    ]
