# Generated by Django 4.2.11 on 2024-04-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_rename_subtotal_labour_total_alter_labour_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour',
            name='title',
        ),
    ]
