# Generated by Django 4.2.11 on 2024-04-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_labour_subtotal_invoice_parts_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='vat_subtotal',
            new_name='vat_total',
        ),
    ]
