# Generated by Django 4.2.11 on 2024-04-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_rename_vat_subtotal_invoice_vat_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='labour_subtotal',
            new_name='labour_total',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='parts_subtotal',
            new_name='parts_total',
        ),
    ]
